services:
  - type: web
    name: TomaszewskiFlask
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python scraper.py
    plan: free
    envVars:
      - key: PORT
        value: 5000
